apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lilly-ingress
spec:
  rules:
  - host: lilly.walkure.net
    http:
      paths:
      - path: /
        backend:
          serviceName: {{active_services.get('api').name}}
          servicePort: 80
  - host: inactive.lilly.walkure.net
    http:
      paths:
      - path: /
        backend:
          serviceName: {{inactive_services.get('api').name}}
          servicePort: 80
